 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/garbages", type: :request do
  # Garbage. As you add validations to Garbage, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Garbage.create! valid_attributes
      get garbages_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      garbage = Garbage.create! valid_attributes
      get garbage_url(garbage)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_garbage_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      garbage = Garbage.create! valid_attributes
      get edit_garbage_url(garbage)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Garbage" do
        expect {
          post garbages_url, params: { garbage: valid_attributes }
        }.to change(Garbage, :count).by(1)
      end

      it "redirects to the created garbage" do
        post garbages_url, params: { garbage: valid_attributes }
        expect(response).to redirect_to(garbage_url(Garbage.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Garbage" do
        expect {
          post garbages_url, params: { garbage: invalid_attributes }
        }.to change(Garbage, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post garbages_url, params: { garbage: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested garbage" do
        garbage = Garbage.create! valid_attributes
        patch garbage_url(garbage), params: { garbage: new_attributes }
        garbage.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the garbage" do
        garbage = Garbage.create! valid_attributes
        patch garbage_url(garbage), params: { garbage: new_attributes }
        garbage.reload
        expect(response).to redirect_to(garbage_url(garbage))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        garbage = Garbage.create! valid_attributes
        patch garbage_url(garbage), params: { garbage: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested garbage" do
      garbage = Garbage.create! valid_attributes
      expect {
        delete garbage_url(garbage)
      }.to change(Garbage, :count).by(-1)
    end

    it "redirects to the garbages list" do
      garbage = Garbage.create! valid_attributes
      delete garbage_url(garbage)
      expect(response).to redirect_to(garbages_url)
    end
  end
end
